### PR TITLE
SSH updates in README.md

### PR DESCRIPTION
**Pull request by smandan**
SSH updates in README.md

### CODE REVIEW

**Comment by XnimrodhunterX** [comment]
update 1

**Comment by peterkempy** [comment]
added ssh keys

**Comment by p-friedmann** [comment]
Test

**Comment by byBinyam** [comment]
Add some information about ssh keys

**Comment by ianzdanowsky** [comment]
added ssh keys info

**Comment by JigishDesai** [comment]
Updated README to include info on ssh key.

**Comment by DMLSMT** [comment]
### ssh keys

**Comment by shivaninagaria** [comment]
added

**Comment by montone** [comment]
Awesome!

**Comment by piquesel** [comment]
Updating README file.

**Pull request closed without merging**
